spring:
  application:
    name: server

  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    url: "jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:folia}"
    username: "${POSTGRES_USER:folia}"
    password: "${POSTGRES_PASSWORD:folia}"

    # Connection Pool
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
      jdbc:
        lob:
          non_textual_creation: true
    show-sql: true

  flyway:
    enabled: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

